{% set version = "1.4-11" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-vcd
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/vcd_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/vcd/vcd_{{ version }}.tar.gz
  sha256: 7a54e855689e1429d46e0d4d7a956f96b0ad2fd0c7084fa023902c55849e0932

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-colorspace
    - r-lmtest
  run:
    - r-base
    - r-mass
    - r-colorspace
    - r-lmtest

test:
  commands:
    - $R -e "library('vcd')"           # [not win]
    - "\"%R%\" -e \"library('vcd')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=vcd
  license: GPL-2.0-only
  summary: Visualization techniques, data sets, summary and inference procedures aimed particularly at categorical data. Special emphasis is given to highly extensible grid graphics. The package was package was originally inspired by the book  "Visualizing Categorical Data" by Michael Friendly and is  now the main support
    package for a new book,  "Discrete Data Analysis with R" by Michael Friendly and  David Meyer (2015).
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
