{% set version = "1.4-8" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-vcd
  version: {{ version|replace("-", "_") }}

source:
  fn: vcd_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/vcd_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/vcd/vcd_{{ version }}.tar.gz
  sha256: 236fcb183152f6e9d131eeb3931d5a064a5ff79be91e4533df9148fd2ff41e0c

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-colorspace
    - r-lmtest
  run:
    - r-base
    - r-mass
    - r-colorspace
    - r-lmtest

test:
  commands:
    - $R -e "library('vcd')"           # [not win]
    - "\"%R%\" -e \"library('vcd')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=vcd
  license: GPL-2
  summary: Visualization techniques, data sets, summary and inference procedures aimed particularly at categorical data. Special emphasis is given to highly extensible grid graphics. The package was package was originally inspired by the book  "Visualizing Categorical Data" by Michael Friendly and is  now the main support
    package for a new book,  "Discrete Data Analysis with R" by Michael Friendly and  David Meyer (2015).
  license_family: GPL2
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
